services:
  web:
    container_name: HayaseDB-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL}
    ports:
      - "${PORT}:80"
    restart: always
    pull_policy: build
